### ISSUE TITLE
Password forgotten email template not found

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/templateeditor#44] opened 2016-04-28 16:57 UTC
![image](https://cloud.githubusercontent.com/assets/3033827/14894228/e8617b32-0d72-11e6-98ac-34fc45aa89dc.png)
using OwnCloud server v9.0.1

all other templates are available, but the password-forgotten template is somehow missing

Hints: I was quickly updating all my mail templates with updated signatures and when I remember correctly, the template was there on the very first time; I didn't changed this template, but changed all other templates. And now it's missing.

I've installed a 2nd owncloud server simultaneously and the password forgotten mail template doesn't exist there, too. So, it's a general issue of owncloud server 9.0.1

**Comment by RealRancor** [comment] 2016-04-28 20:15
Looks to me like the same as https://github.com/owncloud/templateeditor/issues/41

**Comment by VicDeo** [comment] 2017-11-23 17:00
@jochenwezel seems to be fixed with https://github.com/owncloud/templateeditor/pull/42
Is it still reproducible for you?

**Comment by JochenHWezel** [comment] 2017-11-23 17:58
yeah, it's working :-)

**Comment by VicDeo** [comment] 2017-11-23 18:04
@jochenwezel thanks, closing then

**Closed by VicDeo** 2017-11-23 18:04 UTC
